services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped

  web:
    image: ghcr.io/netulo/pplv2:${APP_VERSION:-stable}
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - static_volume:/app/staticfiles
    depends_on:
      - web
    restart: unless-stopped
  
  watchtower:
    image: containrrr/watchtower
    container_name: pplv2_watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json:ro 
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL:-3600}
    profiles:
      - auto-update # Zabezpieczenie - startuje tylko, gdy tego wymusimy

volumes:
  postgres_data:
  static_volume: